# Generated by Django 5.2.17 on 2026-09-01 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_consumption', models.FloatField()),
                ('fuel_consumption', models.FloatField()),
                ('transportation_distance', models.FloatField()),
                ('production_level', models.FloatField()),
                ('predicted_emission', models.FloatField()),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.organization')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_consumption', models.FloatField()),
                ('fuel_consumption', models.FloatField()),
                ('transportation_distance', models.FloatField()),
                ('production_level', models.FloatField()),
                ('total_emission', models.FloatField()),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('recorded_date', models.DateField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.organization')),
            ],
        ),
    ]
