# Generated by Django 5.2.17 on 2026-09-01 12:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_emissionprediction_emissionrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emissionprediction',
            options={'ordering': ['-prediction_date']},
        ),
        migrations.AlterModelOptions(
            name='emissionrecord',
            options={'ordering': ['-recorded_date']},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['organization_name']},
        ),
        migrations.AlterField(
            model_name='emissionprediction',
            name='electricity_consumption',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='emissionprediction',
            name='fuel_consumption',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='emissionprediction',
            name='predicted_emission',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='emissionprediction',
            name='production_level',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='emissionprediction',
            name='transportation_distance',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='electricity_consumption',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='fuel_consumption',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='production_level',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='total_emission',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='transportation_distance',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='CarbonCreditListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price_per_credit', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(default='Available', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarbonCreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price_per_credit', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Completed', max_length=30)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='myapp.organization')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.carboncreditlisting')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='myapp.organization')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='CarbonCreditWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_credits', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.organization')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emission_limit', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('year', models.IntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.organization')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('organization', 'year')},
            },
        ),
    ]
